#!/bin/bash

mkdir -p "$1/build" "$1/hdrs" "$1/srcs"

echo "cmake_minimum_required(VERSION 3.18)
project(Hello LANGUAGES CXX)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE \"Debug\")
endif()

set(CMAKE_CXX_FLAGS_DEBUG \"-O0 -ggdb3\")
set(CMAKE_CXX_FLAGS_RELEASE \"-O3\")

if(CMAKE_CXX_COMPILER_ID MATCHES GNU)
    set(CMAKE_CXX_FLAGS \"\${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -Weffc++ -Wsign-conversion -pedantic-errors -std=c++2a\")
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
    set(CMAKE_CXX_FLAGS \"\${CMAKE_CXX_FLAGS} -Weverything -Wno-vla -Wno-declaration-after-statement\")
endif()

add_library(lib srcs/lib.cpp)
add_executable(main srcs/main.cpp)

target_include_directories(lib PRIVATE hdrs)
target_include_directories(main PRIVATE hdrs)

target_link_libraries(main lib)" > "$1/CMakeLists.txt"

echo "#include \"lib.hpp\"
#include <cstdlib>

int main(void) {
  return EXIT_SUCCESS;
}" > "$1/srcs/main.cpp"

echo "#include \"lib.hpp\"" > "$1/srcs/lib.cpp"

echo "#ifndef LIB_HPP
#define LIB_HPP

#endif" > "$1/hdrs/lib.hpp"

cd "$1/build" && cmake .. && make
